stages:
  get_data:
    cmd: py get_data.py
    deps:
    - get_data.py
    outs:
    - data_raw.csv
  process_data:
    cmd: py process_data.py
    deps:
    - process_data.py
    - data_raw.csv
    outs:
    - data_processed.csv
  train:
    cmd: py train.py
    deps:
    - train.py
    - data_processed.csv
    outs:
    - by_region.png
    metrics:
    - metrics.json:
        cache: false

